import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { SectionWrapper } from './SectionWrapper.js'; // Added .js
import { Card } from './Card.js'; // Added .js
import { PROJECTS_DATA, GitHubIcon } from '../constants.js'; // Added .js
const ExternalLinkIcon = ({ className }) => (_jsx("svg", { xmlns: "http://www.w3.org/2000/svg", fill: "none", viewBox: "0 0 24 24", strokeWidth: 1.5, stroke: "currentColor", className: className || "w-5 h-5 ml-1", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" }) }));
export const Projects = ({ className }) => {
    return (_jsxs(SectionWrapper, { id: "projects", title: "Featured Projects", className: className, children: [_jsx("div", { className: "grid md:grid-cols-2 lg:grid-cols-3 gap-8", children: PROJECTS_DATA.map((project) => (_jsxs(Card, { className: "flex flex-col", children: [_jsx("img", { src: project.imageUrl, alt: project.title, className: "w-full h-48 object-cover rounded-t-lg mb-4" }), _jsxs("div", { className: "flex-grow", children: [_jsx("h3", { className: "text-xl font-semibold text-sky-700 mb-2", children: project.title }), _jsx("p", { className: "text-slate-600 text-sm mb-4 leading-relaxed", children: project.description }), _jsxs("div", { className: "mb-4", children: [_jsx("p", { className: "text-xs text-emerald-700 font-semibold mb-1", children: "Technologies:" }), _jsx("div", { className: "flex flex-wrap gap-2", children: project.technologies.map(tech => (_jsx("span", { className: "bg-emerald-100 text-emerald-800 text-xs px-2 py-1 rounded-full border border-emerald-300", children: tech }, tech))) })] })] }), _jsxs("div", { className: "mt-auto pt-4 border-t border-slate-300 flex justify-end space-x-4", children: [project.repoUrl && (_jsxs("a", { href: project.repoUrl, target: "_blank", rel: "noopener noreferrer", className: "text-slate-600 hover:text-purple-500 transition-colors flex items-center text-sm", "aria-label": `GitHub repository for ${project.title}`, children: [_jsx(GitHubIcon, { className: "w-5 h-5 mr-1" }), " Code"] })), project.liveUrl && project.liveUrl !== "#" && ( // Only show if liveUrl is present and not just "#"
                                _jsxs("a", { href: project.liveUrl, target: "_blank", rel: "noopener noreferrer", className: "text-slate-600 hover:text-purple-500 transition-colors flex items-center text-sm", "aria-label": `Live demo of ${project.title}`, children: [_jsx(ExternalLinkIcon, { className: "w-5 h-5 mr-1" }), " Live Demo"] }))] })] }, project.id))) }), _jsxs("p", { className: "text-center mt-12 text-slate-600", children: ["Note: Project details are placeholders. Please update them with your actual work in ", _jsx("code", { children: "constants.tsx" }), "."] })] }));
};
